version: '3'

services:
  postgres:
    image: 'postgres:13'
    restart: always
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'
    volumes:
      - ./data:/var/lib/postgresql/data